
RandomForest:
  n_estimators: 
    - 10
    - 20
    - 40
  max_depth:
    - 3
    - 5
    - 10
  cv: 10
SVM:
  C:
    - 0.01
    - 0.1
    - 1
    - 10
    - 100
  cv: 5
KNN:
  n_neighbors:
    - 2
    - 4
    - 7
    - 9
    - 15
  # leaf_size:
  #   - 15
  #   - 30
  #   - 45
  cv: 5
NB:
  alpha:
    - 1
    - 2
    - 3 