# Baseline approaches
InAll:
  - simplistic_approach
ExAll:
  - delete_all_literals
# InNumbers:
#   - delete_all_but_numbers
# InDates:
#   - delete_all_but_dates
# InText:
#   - delete_all_but_text
# InImages:
#   - delete_all_but_images
# ExNumbers:
#   - delete_numbers
# ExDates:
#   - delete_dates
# ExText:
#   - delete_text
# ExImages:
#   - delete_images
# OneEntPerRel:
#   - one_entity