file_paths:
  preprocessed: data/preprocessed
  embedded: data/embedded
  predicted: data/predicted


dataload:
  amplus:
    use_final_distribution : True # get train test split instead of train valid split?
    use_torch : True #use torch?
    prune_dist : 25 #reduce the number of triples to an n-hop neighborhood around the labeled nodes?
  dmgfull:
    use_final_distribution : True # get train test split instead of train valid split?
    use_torch : True #use torch?
    prune_dist : 25 #reduce the number of triples to an n-hop neighborhood around the labeled nodes?
  mdgenre:
    use_final_distribution : True # get train test split instead of train valid split?
    use_torch : True #use torch?
    prune_dist : 25 #reduce the number of triples to an n-hop neighborhood around the labeled nodes?
  dmg777k: 
    use_final_distribution : True # get train test split instead of train valid split?
    use_torch : True #use torch?
    prune_dist : 25 #reduce the number of triples to an n-hop neighborhood around the labeled nodes?


preprocess:
  bin_numbers2:
    num_bins: 10
  append_weekday_and_month:
    neighborhood: 1
  delete_number_literals:
    neighborhood: 1
  do_nothing:
    nothingness: true
  delete_all_literals:
    neighborhood: 1
  delete_all_but_numbers:
    neighborhood: 1
  one_entity:
    num_bins: 1
  bin_numbers_3:
    num_bins: 3
  bin_numbers_10:
    num_bins: 10
  bin_numbers_100:
    num_bins: 100
  bin_numbers_lof_3:
    num_bins: 3
  bin_numbers_lof_10:
    num_bins: 10
  bin_numbers_lof_100:
    num_bins: 100
  altering_bins:
    num_bins: 10


embed:
  RDF2Vec: 
    embedding_name: Word2Vec
    embedding_args:
      workers: 4
      epochs: 40
    walker_name: RandomWalker
    walker_args:
      max_depth: 3 # change to 2
      max_walks: 500
  RDF2Vec2: 
    embedding_name: Word2Vec
    embedding_args:
      workers: 4
      epochs: 40
    walker_name: RandomWalker
    walker_args:
      max_depth: 2
  TransE:
    optimizer: Adam 
    train_loop_type: SLCWA
    train_loop_args:
      num_epochs: 40
      batch_size: 2048
  complex:
    optimizer: Adam 
    train_loop_type: SLCWA
    train_loop_args:
      num_epochs: 30
      batch_size: 1024
  RGCN:
    optimizer: Adam 
    train_loop_type: SLCWA
    train_loop_args:
      num_epochs: 30
      batch_size: 1024
  



evaluate:
  RandomForest:
    n_estimators: 
      - 10
      - 20
      - 40
    max_depth:
      - 3
      - 5
      - 10
    cv: 10
  SVM:
    C:
      - 0.01
      - 0.1
      - 1
      - 10
      - 100
      - 1000 

    cv: 10
  KNN:
    n_neighbors:
      - 2
      - 4
      - 7
      - 9
      - 15
    leaf_size:
      - 10
      - 20
      - 30
      - 50
  NB:
    alpha:
      - 1
      - 2
      - 3 

pipeline:
  dataload: amplus
  preprocess: 
  #  - do_nothing
  
    - bin_numbers_3
    - delete_number_literals
  #  - delete_all_literals
  #  - delete_number_literals
  #  - bin_numbers2
  embed: TransE
  evaluate: 
    - SVM
    - KNN
  #  - NB

pipeline_schedule:
  dataload:
    - amplus
    - dmg777k
    - mdgenre
  #  - dmg777k
  preprocess:
    # H1
    -
      - delete_all_literals
    -
      - do_nothing

    # Baselines
    -
      - one_entity
      - delete_all_literals
    -
      - delete_number_literals
    #-
    #  - bin_numbers2
    #  - delete_number_literals

    # H2
    # bin
    -
      - bin_numbers_3
      - delete_number_literals
    -
      - bin_numbers_10
      - delete_number_literals
    -
      - bin_numbers_100
      - delete_number_literals
    # bin + lof
    -
      - bin_numbers_lof_3
      - delete_number_literals
    -
      - bin_numbers_lof_10
      - delete_number_literals
    -
      - bin_numbers_lof_100
      - delete_number_literals
    
    # simmilar paper
    -
      - bin_numbers_3
      - bin_numbers_10
      - bin_numbers_100
      - delete_number_literals
    -
      - altering_bins
      - delete_number_literals
  embed:
    - TransE
    #- RDF2Vec
    - RDF2Vec2
  iterations: 1

