defaults:
  - dataload: dataload
  - aug_method: methods
  - aug_approach: approach
  - embed: embed
  - evaluate: evaluate
  - pipeline: default
  - _self_
file_paths:
  preprocessed: data/preprocessed
  embedded: data/embedded
  predicted: data/predicted
schedule:
  dataload:
    - dmg777k
    - amplus
    - mdgenre
    - dmgfull

  augment:
    - InAll
    - ExAll

    - InNumbers
    - InDates
    - InText
    - InImages
    
    - ExNumbers
    - ExDates
    - ExText
    - ExImages

    - OneEntPerRel

    - 5_bins
    - 10_bins
    - 100_bins

    - 5_lof_bins
    - 10_lof_bins
    - 100_lof_bins

    - 1_pct_bins
    - 5_pct_bins
    - 10_pct_bins


  embed:
    - TransE
    - DistMult
    - RDF2Vec
  iterations: 1

