defaults:
  - dataload: dataload
  - aug_method: methods
  - aug_approach: approach
  - embed: embed
  - evaluate: evaluate
  - _self_

file_paths:
  preprocessed: data/preprocessed
  embedded: data/embedded
  predicted: data/predicted

pipeline:
  dataload: dmgfull
  augment: bin_3
  embed: SimplE
  evaluate: 
    - SVM
    - KNN


